//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはツールによって生成されました。
//     ランタイム バージョン:4.0.30319.42000
//
//     このファイルへの変更は、以下の状況下で不正な動作の原因になったり、
//     コードが再生成されるときに損失したりします。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ShibugakiViewer.Properties {
    using System;
    
    
    /// <summary>
    ///   ローカライズされた文字列などを検索するための、厳密に型指定されたリソース クラスです。
    /// </summary>
    // このクラスは StronglyTypedResourceBuilder クラスが ResGen
    // または Visual Studio のようなツールを使用して自動生成されました。
    // メンバーを追加または削除するには、.ResX ファイルを編集して、/str オプションと共に
    // ResGen を実行し直すか、または VS プロジェクトをビルドし直します。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   このクラスで使用されているキャッシュされた ResourceManager インスタンスを返します。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ShibugakiViewer.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   厳密に型指定されたこのリソース クラスを使用して、すべての検索リソースに対し、
        ///   現在のスレッドの CurrentUICulture プロパティをオーバーライドします。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Add に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string AddButton_ToolTip {
            get {
                return ResourceManager.GetString("AddButton_ToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Add new condition に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string AddConditionButton_ToolTip {
            get {
                return ResourceManager.GetString("AddConditionButton_ToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Added に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string AddedText {
            get {
                return ResourceManager.GetString("AddedText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Advanced Settings に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string AdvancedSettingsSwitch_Header {
            get {
                return ResourceManager.GetString("AdvancedSettingsSwitch_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Play Animated GIF に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string AnimatedGifSwitch_Text {
            get {
                return ResourceManager.GetString("AnimatedGifSwitch_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   App に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string App {
            get {
                return ResourceManager.GetString("App", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ascending に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Ascending {
            get {
                return ResourceManager.GetString("Ascending", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Aspect Ratio (W/H) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string AspectRatio {
            get {
                return ResourceManager.GetString("AspectRatio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Automatic Zoom に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string AutomaticZoomHelp_Text {
            get {
                return ResourceManager.GetString("AutomaticZoomHelp_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Update Automatically when the App is Launched に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string AutoRefereshHelp_Text {
            get {
                return ResourceManager.GetString("AutoRefereshHelp_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Back に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string BackButton_ToolTip {
            get {
                return ResourceManager.GetString("BackButton_ToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Back に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string BackHelp_Text {
            get {
                return ResourceManager.GetString("BackHelp_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///    に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string BelowRef {
            get {
                return ResourceManager.GetString("BelowRef", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cancel に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string CancelButton_Content {
            get {
                return ResourceManager.GetString("CancelButton_Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Change Referenced Folder に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ChangeFolderButton_Content {
            get {
                return ResourceManager.GetString("ChangeFolderButton_Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Clear Selection に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ClearSelectionButton_Label {
            get {
                return ResourceManager.GetString("ClearSelectionButton_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Use color management に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string CmsSwitch_Header {
            get {
                return ResourceManager.GetString("CmsSwitch_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Common Rating に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string CommonRating {
            get {
                return ResourceManager.GetString("CommonRating", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Common Tags に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string CommonTag {
            get {
                return ResourceManager.GetString("CommonTag", resourceCulture);
            }
        }
        
        /// <summary>
        ///   contains に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Contains {
            get {
                return ResourceManager.GetString("Contains", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Copy Path に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string CopyPath {
            get {
                return ResourceManager.GetString("CopyPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Function of Cursor Keys に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string CursorKeyFuncHelp_Header {
            get {
                return ResourceManager.GetString("CursorKeyFuncHelp_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Flip or Zoom Image に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string CursorKeyToFlipHelp_Content {
            get {
                return ResourceManager.GetString("CursorKeyToFlipHelp_Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Move Image に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string CursorKeyToMoveHelp_Content {
            get {
                return ResourceManager.GetString("CursorKeyToMoveHelp_Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Black に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string DarkText_Text {
            get {
                return ResourceManager.GetString("DarkText_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Created Date に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string DateCreated {
            get {
                return ResourceManager.GetString("DateCreated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Modified Date に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string DateModified {
            get {
                return ResourceManager.GetString("DateModified", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Registered Date に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string DateRegistered {
            get {
                return ResourceManager.GetString("DateRegistered", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Decrease Rating に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string DecreaseRatingHelp_Text {
            get {
                return ResourceManager.GetString("DecreaseRatingHelp_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Default に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Default {
            get {
                return ResourceManager.GetString("Default", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Descending に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Descending {
            get {
                return ResourceManager.GetString("Descending", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Directory に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Directory {
            get {
                return ResourceManager.GetString("Directory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Directory Path に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string DirectoryPath {
            get {
                return ResourceManager.GetString("DirectoryPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Directory (Contains) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string DirectoryPathContains {
            get {
                return ResourceManager.GetString("DirectoryPathContains", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Use transparent buttons to change image に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string DisableMoveButton {
            get {
                return ResourceManager.GetString("DisableMoveButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Display and Navigation に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string DispAndNaviHelp_Text {
            get {
                return ResourceManager.GetString("DispAndNaviHelp_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Show Properties に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string DispPropHelp_Text {
            get {
                return ResourceManager.GetString("DispPropHelp_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Search Result Layout に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string DispSearchResultHelp_Text {
            get {
                return ResourceManager.GetString("DispSearchResultHelp_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   does not contain に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string DoNotContains {
            get {
                return ResourceManager.GetString("DoNotContains", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Down に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Down {
            get {
                return ResourceManager.GetString("Down", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Duration に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string DurationText_Text {
            get {
                return ResourceManager.GetString("DurationText_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Edit に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string EditButton_ToolTip {
            get {
                return ResourceManager.GetString("EditButton_ToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   is equal to (==) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string EqualsTo {
            get {
                return ResourceManager.GetString("EqualsTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Exit に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Exit {
            get {
                return ResourceManager.GetString("Exit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Exit this Application に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ExitApp {
            get {
                return ResourceManager.GetString("ExitApp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Export/Import に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ExportImport {
            get {
                return ResourceManager.GetString("ExportImport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Export/Import Library に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ExportImportLibrary {
            get {
                return ResourceManager.GetString("ExportImportLibrary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   To export/import the library, the application&apos;s windows will be closed. Do you want to continue? に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ExportImportLibraryMessage {
            get {
                return ResourceManager.GetString("ExportImportLibraryMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Export Library に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ExportLibrary {
            get {
                return ResourceManager.GetString("ExportLibrary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Use extended mouse buttons to change the image に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ExtendedMouseSwitch_Text {
            get {
                return ResourceManager.GetString("ExtendedMouseSwitch_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Add to Albums に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string FavoriteButton_ToolTip {
            get {
                return ResourceManager.GetString("FavoriteButton_ToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Album に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string FavoriteText_Text {
            get {
                return ResourceManager.GetString("FavoriteText_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Contains に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string FileCount {
            get {
                return ResourceManager.GetString("FileCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   File Name に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string FileName {
            get {
                return ResourceManager.GetString("FileName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   File Name (Contains) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string FileNameContains {
            get {
                return ResourceManager.GetString("FileNameContains", resourceCulture);
            }
        }
        
        /// <summary>
        ///   File Name (Left Sequence Number) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string FileNameSequenceNumLeft {
            get {
                return ResourceManager.GetString("FileNameSequenceNumLeft", resourceCulture);
            }
        }
        
        /// <summary>
        ///   File Name (Right Sequence Number) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string FileNameSequenceNumRight {
            get {
                return ResourceManager.GetString("FileNameSequenceNumRight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   File Operation に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string FileOperation {
            get {
                return ResourceManager.GetString("FileOperation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   File Property に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string FilePropertyText_Text {
            get {
                return ResourceManager.GetString("FilePropertyText_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   File Size に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string FileSize {
            get {
                return ResourceManager.GetString("FileSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Fill に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string FillText_Content {
            get {
                return ResourceManager.GetString("FillText_Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Fit に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string FitText_Content {
            get {
                return ResourceManager.GetString("FitText_Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Fix the Bar に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string FixButton_Label {
            get {
                return ResourceManager.GetString("FixButton_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Always animate page flip に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string FlipAnimationSwitch_Text {
            get {
                return ResourceManager.GetString("FlipAnimationSwitch_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Flip Horizontal に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string FlipHorizontalHelp_Text {
            get {
                return ResourceManager.GetString("FlipHorizontalHelp_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Left to Right に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string FlipNormal {
            get {
                return ResourceManager.GetString("FlipNormal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Right to Left に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string FlipReverse {
            get {
                return ResourceManager.GetString("FlipReverse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Flip Vertical に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string FlipVerticalHelp_Text {
            get {
                return ResourceManager.GetString("FlipVerticalHelp_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Folder Management に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string FolderManagement {
            get {
                return ResourceManager.GetString("FolderManagement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Folders to load Images に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string FolderManagePageTitle_Text {
            get {
                return ResourceManager.GetString("FolderManagePageTitle_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Add Folder に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string FolderPageButton_Label {
            get {
                return ResourceManager.GetString("FolderPageButton_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   File Path に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string FolderRelativeId {
            get {
                return ResourceManager.GetString("FolderRelativeId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   File Path に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string FullPath {
            get {
                return ResourceManager.GetString("FullPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Full-screen Slideshow に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string FullscreenText_Text {
            get {
                return ResourceManager.GetString("FullscreenText_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   is greater or equal to (&gt;=) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string GreaterEqual {
            get {
                return ResourceManager.GetString("GreaterEqual", resourceCulture);
            }
        }
        
        /// <summary>
        ///   is greater than (&gt;) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string GreaterThan {
            get {
                return ResourceManager.GetString("GreaterThan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Display Group Contents に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string GroupDisplay {
            get {
                return ResourceManager.GetString("GroupDisplay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Grouping に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string GroupingButton_Label {
            get {
                return ResourceManager.GetString("GroupingButton_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Use Grouping に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string GroupingSwitch_Header {
            get {
                return ResourceManager.GetString("GroupingSwitch_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   GroupLeader に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string GroupLeader {
            get {
                return ResourceManager.GetString("GroupLeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Group Name に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string GroupName {
            get {
                return ResourceManager.GetString("GroupName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Group Property に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string GroupProperty {
            get {
                return ResourceManager.GetString("GroupProperty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Height に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Height {
            get {
                return ResourceManager.GetString("Height", resourceCulture);
            }
        }
        
        /// <summary>
        ///   History に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string HistoryText_Text {
            get {
                return ResourceManager.GetString("HistoryText_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Image Library に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ImageLibraryLabel_Text {
            get {
                return ResourceManager.GetString("ImageLibraryLabel_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Images Selected に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ImageSelectedTaxt_Text {
            get {
                return ResourceManager.GetString("ImageSelectedTaxt_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Image Size に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ImageSize {
            get {
                return ResourceManager.GetString("ImageSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   items に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ImageUnitLabel_Text {
            get {
                return ResourceManager.GetString("ImageUnitLabel_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Import Library に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ImportLibrary {
            get {
                return ResourceManager.GetString("ImportLibrary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Import from MikanViewer に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ImportMikanViewer {
            get {
                return ResourceManager.GetString("ImportMikanViewer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Increase Rating に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string IncreaseRatingHelp_Text {
            get {
                return ResourceManager.GetString("IncreaseRatingHelp_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Information に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string InformationText_Text {
            get {
                return ResourceManager.GetString("InformationText_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   is に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Is {
            get {
                return ResourceManager.GetString("Is", resourceCulture);
            }
        }
        
        /// <summary>
        ///   is not に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string IsNot {
            get {
                return ResourceManager.GetString("IsNot", resourceCulture);
            }
        }
        
        /// <summary>
        ///    に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string IsV {
            get {
                return ResourceManager.GetString("IsV", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Key Binds に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string KeyBindHelp_Text {
            get {
                return ResourceManager.GetString("KeyBindHelp_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Enabled when keyboard is connected_ に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string KeyboardHelp_Text {
            get {
                return ResourceManager.GetString("KeyboardHelp_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Keyboard Shortcut に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string KeyShortcut {
            get {
                return ResourceManager.GetString("KeyShortcut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   en-US に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Language {
            get {
                return ResourceManager.GetString("Language", resourceCulture);
            }
        }
        
        /// <summary>
        ///   is less or equal to (&lt;=) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string LessEqual {
            get {
                return ResourceManager.GetString("LessEqual", resourceCulture);
            }
        }
        
        /// <summary>
        ///   is less than (&lt;) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string LessThan {
            get {
                return ResourceManager.GetString("LessThan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Library に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Library {
            get {
                return ResourceManager.GetString("Library", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Search Options に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string LibrarySettings_Text {
            get {
                return ResourceManager.GetString("LibrarySettings_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Library Update Status に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string LibraryUpdateStatus {
            get {
                return ResourceManager.GetString("LibraryUpdateStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Library Update Mode に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string LibRefreshModeHelp_Header {
            get {
                return ResourceManager.GetString("LibRefreshModeHelp_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   License に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string LicenseTitle_Text {
            get {
                return ResourceManager.GetString("LicenseTitle_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   White に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string LightText_Text {
            get {
                return ResourceManager.GetString("LightText_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Set Lock Screen に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string LockScreenText_Text {
            get {
                return ResourceManager.GetString("LockScreenText_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Set Lock Screen に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string LockScreenTextLabel_Label {
            get {
                return ResourceManager.GetString("LockScreenTextLabel_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   match all (AND) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MatchAll {
            get {
                return ResourceManager.GetString("MatchAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   match any (OR) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MatchAny {
            get {
                return ResourceManager.GetString("MatchAny", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Menu に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MenuButton_ToolTip {
            get {
                return ResourceManager.GetString("MenuButton_ToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Flip Horizontal に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MirrorHorizontalText_Text {
            get {
                return ResourceManager.GetString("MirrorHorizontalText_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Flip Vertical に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MirrorVerticalText_Text {
            get {
                return ResourceManager.GetString("MirrorVerticalText_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Move Image に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MoveImageHelp_Text {
            get {
                return ResourceManager.GetString("MoveImageHelp_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Name に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Name {
            get {
                return ResourceManager.GetString("Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   New Search に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string NewSearchText_Text {
            get {
                return ResourceManager.GetString("NewSearchText_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   New Tag に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string NewTag {
            get {
                return ResourceManager.GetString("NewTag", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Next Image に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string NextImage {
            get {
                return ResourceManager.GetString("NextImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   No image files in all the folders. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string NoImageText1_Text {
            get {
                return ResourceManager.GetString("NoImageText1_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Please register the folder that contains image files. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string NoImageText2_Text {
            get {
                return ResourceManager.GetString("NoImageText2_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   is not equal to (!=) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string NotEqualsTo {
            get {
                return ResourceManager.GetString("NotEqualsTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Numerical Value に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string NumericTextBox_PlaceholderText {
            get {
                return ResourceManager.GetString("NumericTextBox_PlaceholderText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Number of tags に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string NumOfTags {
            get {
                return ResourceManager.GetString("NumOfTags", resourceCulture);
            }
        }
        
        /// <summary>
        ///   OK に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string OkButton_Content {
            get {
                return ResourceManager.GetString("OkButton_Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Open file location に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string OpenFileLocation {
            get {
                return ResourceManager.GetString("OpenFileLocation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Open navigation with single tap に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string OpenNaviSingleTapSwitch_Text {
            get {
                return ResourceManager.GetString("OpenNaviSingleTapSwitch_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Open New Window に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string OpenNewWindow {
            get {
                return ResourceManager.GetString("OpenNewWindow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Open in Another App に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string OpenWith {
            get {
                return ResourceManager.GetString("OpenWith", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Options に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Options {
            get {
                return ResourceManager.GetString("Options", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Page-Turning に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string PageTurning {
            get {
                return ResourceManager.GetString("PageTurning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Inline に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string PaneFixButton_ToolTip {
            get {
                return ResourceManager.GetString("PaneFixButton_ToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Path に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Path {
            get {
                return ResourceManager.GetString("Path", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Pause に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string PauseButton_Label {
            get {
                return ResourceManager.GetString("PauseButton_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Play Slideshow に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string PlaySlideShow {
            get {
                return ResourceManager.GetString("PlaySlideShow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Previous Image に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string PreviousImage {
            get {
                return ResourceManager.GetString("PreviousImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Privacy Policy に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string PrivacyPolicy_Text {
            get {
                return ResourceManager.GetString("PrivacyPolicy_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Properties に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string PropertiesButton_ToolTip {
            get {
                return ResourceManager.GetString("PropertiesButton_ToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Properties に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Property {
            get {
                return ResourceManager.GetString("Property", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Purchase に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string PurchaseButton_Content {
            get {
                return ResourceManager.GetString("PurchaseButton_Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   In-App Purchase に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string PurchaseFlyoutTitle_Text {
            get {
                return ResourceManager.GetString("PurchaseFlyoutTitle_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Rating に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Rating {
            get {
                return ResourceManager.GetString("Rating", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Refresh に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Refresh {
            get {
                return ResourceManager.GetString("Refresh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Library has been Updated に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string RefreshedText {
            get {
                return ResourceManager.GetString("RefreshedText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Notify when the library is updated に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string RefreshFolderVisibleHelp_Header {
            get {
                return ResourceManager.GetString("RefreshFolderVisibleHelp_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Update Library に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string RefreshLibrary {
            get {
                return ResourceManager.GetString("RefreshLibrary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Update Mode に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string RefreshMode {
            get {
                return ResourceManager.GetString("RefreshMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Use Default Setting に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string RefreshModeDefault {
            get {
                return ResourceManager.GetString("RefreshModeDefault", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Quickly : Check only the presence of image に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string RefreshModeFast {
            get {
                return ResourceManager.GetString("RefreshModeFast", resourceCulture);
            }
        }
        
        /// <summary>
        ///   In Detail : Check image content change に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string RefreshModeSlow {
            get {
                return ResourceManager.GetString("RefreshModeSlow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Register Folders に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string RegisterFolderButton_Content {
            get {
                return ResourceManager.GetString("RegisterFolderButton_Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Relative Path に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string RelativePath {
            get {
                return ResourceManager.GetString("RelativePath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Relative Path (Sequence Number) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string RelativePathSequenceNum {
            get {
                return ResourceManager.GetString("RelativePathSequenceNum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   You can purchase a license to remove Ads. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string RemoveAdsHelp_Text {
            get {
                return ResourceManager.GetString("RemoveAdsHelp_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Remove Ads に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string RemoveAdsTitle_Text {
            get {
                return ResourceManager.GetString("RemoveAdsTitle_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Remove に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string RemoveButton_Label {
            get {
                return ResourceManager.GetString("RemoveButton_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Remove from Group に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string RemoveButton_ToolTip {
            get {
                return ResourceManager.GetString("RemoveButton_ToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Removed に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string RemovedText {
            get {
                return ResourceManager.GetString("RemovedText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Unregister に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string RemoveFolderButton_Content {
            get {
                return ResourceManager.GetString("RemoveFolderButton_Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Remove に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string RemoveSimpleButton_ToolTip {
            get {
                return ResourceManager.GetString("RemoveSimpleButton_ToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Resizing Method に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ResizeMethodText_Text {
            get {
                return ResourceManager.GetString("ResizeMethodText_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Resize Small Image に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ResizeSmallImageText_Text {
            get {
                return ResourceManager.GetString("ResizeSmallImageText_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   RootDirectoryAccessToken に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string RootDirectoryAccessToken {
            get {
                return ResourceManager.GetString("RootDirectoryAccessToken", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Scaling and Rotation に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string RotateButton_Label {
            get {
                return ResourceManager.GetString("RotateButton_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Rotate Left 90deg に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string RotateCcwText_Text {
            get {
                return ResourceManager.GetString("RotateCcwText_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Rotate Right 90deg に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string RotateCwText_Text {
            get {
                return ResourceManager.GetString("RotateCwText_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Rotate Left 90deg に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string RotateLeftHelp_Text {
            get {
                return ResourceManager.GetString("RotateLeftHelp_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Rotate Right 90deg に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string RotateRightHelp_Text {
            get {
                return ResourceManager.GetString("RotateRightHelp_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Search に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Search {
            get {
                return ResourceManager.GetString("Search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Search Criteria に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string SearchCriteria {
            get {
                return ResourceManager.GetString("SearchCriteria", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Tap Add( に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string SearchHelpText1_Text {
            get {
                return ResourceManager.GetString("SearchHelpText1_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ) button to filter images に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string SearchHelpText2_Text {
            get {
                return ResourceManager.GetString("SearchHelpText2_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Search に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string SearchLabel {
            get {
                return ResourceManager.GetString("SearchLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Search for Images に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string SearchTitleText_Text {
            get {
                return ResourceManager.GetString("SearchTitleText_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Seconds に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string SecondsText_Text {
            get {
                return ResourceManager.GetString("SecondsText_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Select All に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string SelectAllButton_Label {
            get {
                return ResourceManager.GetString("SelectAllButton_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Set to Group Thumbnail に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string SetGroupThumbnail {
            get {
                return ResourceManager.GetString("SetGroupThumbnail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Set to Thumbnail に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string SetThumbnail {
            get {
                return ResourceManager.GetString("SetThumbnail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Settings に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Settings_Text {
            get {
                return ResourceManager.GetString("Settings_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Settings に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string SettingsButton_Label {
            get {
                return ResourceManager.GetString("SettingsButton_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Share に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Share {
            get {
                return ResourceManager.GetString("Share", resourceCulture);
            }
        }
        
        /// <summary>
        ///   This image に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ShareImageTitle {
            get {
                return ResourceManager.GetString("ShareImageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Shuffle に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ShuffleButton_Label {
            get {
                return ResourceManager.GetString("ShuffleButton_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Slideshow に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Slideshow {
            get {
                return ResourceManager.GetString("Slideshow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Slideshow Settings に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string SlideshowSetting_Text {
            get {
                return ResourceManager.GetString("SlideshowSetting_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sort に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Sort {
            get {
                return ResourceManager.GetString("Sort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Start に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string StartButton_Content {
            get {
                return ResourceManager.GetString("StartButton_Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Stop Slideshow に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string StopSlideshow {
            get {
                return ResourceManager.GetString("StopSlideshow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Text に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string StringTextBox_PlaceholderText {
            get {
                return ResourceManager.GetString("StringTextBox_PlaceholderText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Switch に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string SwitchLabel {
            get {
                return ResourceManager.GetString("SwitchLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Tag に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Tag {
            get {
                return ResourceManager.GetString("Tag", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Add Tag に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string TagAdd {
            get {
                return ResourceManager.GetString("TagAdd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Tag Name に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string TagNameBox_PlaceholderText {
            get {
                return ResourceManager.GetString("TagNameBox_PlaceholderText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Remove Tag に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string TagRemove {
            get {
                return ResourceManager.GetString("TagRemove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Tags に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Tags {
            get {
                return ResourceManager.GetString("Tags", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Select Tag に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string TagSelectorHelp_Text {
            get {
                return ResourceManager.GetString("TagSelectorHelp_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Shortcuts for Tag に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string TagShortcutHelp_Text {
            get {
                return ResourceManager.GetString("TagShortcutHelp_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Toolbar Color に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ThemeSelectorHeader_Text {
            get {
                return ResourceManager.GetString("ThemeSelectorHeader_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Thumbnail Size に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ThumbSizeSelector_Header {
            get {
                return ResourceManager.GetString("ThumbSizeSelector_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Tools に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Tools {
            get {
                return ResourceManager.GetString("Tools", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Transition Time に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string TransitionTimeText_Text {
            get {
                return ResourceManager.GetString("TransitionTimeText_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   This app loads image files from user&apos;s &quot;Pictures&quot; folder. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string TutorialText1_Text {
            get {
                return ResourceManager.GetString("TutorialText1_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Tap &quot;Register folders&quot; if you want to load more images from other folders. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string TutorialText2_Text {
            get {
                return ResourceManager.GetString("TutorialText2_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Checking images in folders に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string TutorialText3_Text {
            get {
                return ResourceManager.GetString("TutorialText3_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   This may take several minutes. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string TutorialText4_Text {
            get {
                return ResourceManager.GetString("TutorialText4_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Undo Removal に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string UndoRemovalButton_Label {
            get {
                return ResourceManager.GetString("UndoRemovalButton_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Remove from Album に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string UnFavoriteButton_ToolTip {
            get {
                return ResourceManager.GetString("UnFavoriteButton_ToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Images に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string UnitText {
            get {
                return ResourceManager.GetString("UnitText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Images に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string UnitTextFull {
            get {
                return ResourceManager.GetString("UnitTextFull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Up に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Up {
            get {
                return ResourceManager.GetString("Up", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Updated に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string UpdatedText {
            get {
                return ResourceManager.GetString("UpdatedText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Join Mass Update に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string UpdateEnabledCheckBox_Content {
            get {
                return ResourceManager.GetString("UpdateEnabledCheckBox_Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Updating will be started after page transition. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string UpdateFlagLabel_Text {
            get {
                return ResourceManager.GetString("UpdateFlagLabel_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Update Now に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string UpdateNowButton_Content {
            get {
                return ResourceManager.GetString("UpdateNowButton_Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Updating... に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string UpdatingText_Text {
            get {
                return ResourceManager.GetString("UpdatingText_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Version Information に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Version_Text {
            get {
                return ResourceManager.GetString("Version_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Viewer に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Viewer {
            get {
                return ResourceManager.GetString("Viewer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Viewer Options に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ViewerSettings_Text {
            get {
                return ResourceManager.GetString("ViewerSettings_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Welcome to に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string WelcomeText1_Text {
            get {
                return ResourceManager.GetString("WelcomeText1_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ! に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string WelcomeText2_Text {
            get {
                return ResourceManager.GetString("WelcomeText2_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Width に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Width {
            get {
                return ResourceManager.GetString("Width", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Zoom In に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ZoomInHelp_Text {
            get {
                return ResourceManager.GetString("ZoomInHelp_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Zoom Out に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ZoomOutHelp_Text {
            get {
                return ResourceManager.GetString("ZoomOutHelp_Text", resourceCulture);
            }
        }
    }
}
